project:
  type: website
  output-dir: docs

website:
  title: "An Bui"
  favicon: images/waves.png
  navbar:
    title: An Bui
    left:
      - text: Teaching
        href: teaching.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Data Science
        href: data-science.qmd
      - text: Fieldwork
        href: fieldwork.qmd
      - text: CV
        href: CV/Bui-An_CV.pdf
      - icon: palette-fill
        href: https://an-bui.github.io/shop/
      - icon: github
        href: https://github.com/an-bui
        
reader-mode: true

format:
  html:
    theme: 
    - lux
    - custom.scss
    mainfont: Raleway
    css: styles.css
    toc: true

editor: visual

