---
title: "Letters of recommendation"
editor: source
---

## What should I look for in someone to write a letter of recommendation?

A letter of rec should speak to your abilities and fit for the position you're applying for. Thus, the person writing that letter should be able to attest to your potential success in that position!  

Your letter writer should be able to write a _strong_, _specific_ letter to endorse you for a given position. A _vague_, _generic_ letter is a detriment to you - for most jobs or grad schools, you would be in the best position possible if you get a strong letter speaking to your specific expertise.  

Unfortunately, not all professors can write you a strong letter. If you attended class but never spoke to me about anything other than class information, I wouldn't be able to write you a strong letter because I don't know what your goals are, your plans for the future, etc. 

## What do you typically include in a letter of rec?

In letters, I typically discuss:  

- your abilities to problem solve  
- any projects or assignments you've done that stand out  
- your ability to work together with others in collaborative contexts (very important!!)  
- your ability to support other people in their learning journey (also very important!!)  

## What do I need to do to get a letter of recommendation from you?

These are guidelines, not rules. Broadly, I need to understand you as a person outside of being a student in my classes!  

Generally, you could ask me for a letter if you have:  

- talked to me at least _once_ about post-grad plans  
- actively participated in class (e.g. engaging with learning partners in coding workshop, asking and answering questions in lecture)  
- demonstrated meaningful success in a course I have taught (clear improvement and development of your thinking - this is not tied to your letter grade!)  

Please note that these are rough suggestions but not requirements. You are the best judge of your relationship with me (outside of, well, me!), so you are of course welcome to ask for a letter even if these suggestions do not apply to you.

## If I do these things, am I guaranteed to get a letter from you?

_No_. I will seriously consider any request for a letter. However, I cannot write you a strong letter, I will tell you directly.  

Additionally, if you are applying to the [Bren Masters in Environmental Data Science program](https://bren.ucsb.edu/masters-programs/master-environmental-data-science), I may ask you for a one-on-one meeting to discuss the program further.

## I am sure I want a letter from you! What do I do?

Email me with the following information:  

- some basic information about you (how we know each other, some assignments/projects you worked on with me that demonstrate the development of your skills and abilities)  
- the jobs/schools you are applying for  
- the deadlines for letter submission for each job/school  
