---
title: "Publications"
editor: source
---

**Please see my** [CV](CV/Bui-An_CV.pdf) **for a complete list of publications and talks.**

## Accepted

<ol reversed>

<li> Joyce, FH, JA Rosales, KD Holl, RA Zahawi, **A Bui**, JL Reid. "Active restoration accelerates recovery of tropical forest bird assemblages over two decades." *Biological Conservation.* 2024. [PDF](paper-pdfs/joyce-2024.pdf)

<li> Guerra, AS, **A Bui**, M Klope, DA Orr, SA Shaffer, HS Young. "Leaving more than footprints: anthropogenic nutrient subsidies to a protected area." *Ecosphere.* 2022. [PDF](paper-pdfs/guerra-2022.pdf)  
{{< fa newspaper >}} **Media coverage**: [Los Angeles Times](https://www.latimes.com/environment/story/2019-10-22/seagulls-poop-changing-channel-islands-chemistry)</li>

<li> Miller-ter Kuile, A, A Apigo, **A Bui**, K Butner, JN Childress, S Copeland, BP DiFiore, ES Forbes, M Klope, CI Motta, D Orr, KA Plummer, DL Preston, HS Young "Changes in invertebrate food web structure between high- and low-productivity environments are driven by intermediate but not top-predator diet shifts." *Biology Letters.* 2022. [PDF](paper-pdfs/miller-ter-kuile-2022-biolett.pdf).</li>

<li> Ingeman, KE, C Wolf, DR Williams, LZ Zhao, AL Ritger, WJ Ripple, KL Kopecky, EM Dillon, BP DiFiore, SR Csik, **A Bui**, AC Stier. "Glimmers of Hope in Global Apex Predator Recovery." *Scientific Reports.* 2022. [PDF](paper-pdfs/ingeman-2022.pdf).</li>

<li> Orr, D, **A Bui**, MM Klope, M Lee, I McCullough, CI Motta, I Mayorga, K Konicek, K, HS Young. "Context-dependent effects of shifting large herbivore assemblages on plant structure and diversity." *Journal of Ecology.* 2022. [PDF](paper-pdfs/orr-2022.pdf).</li>

<li> Miller-ter Kuile, A, A Apigo, **A Bui**, B DiFiore, ES Forbes, M Lee, D Orr, DL Preston, R Behm, T Bogar, J Childress, R Dirzo, M Klope, KD Lafferty, J McLaughlin, M Morse, C Motta, K Park, K Plummer, D Weber, R Young, H Young. "Predator-prey interactions of terrestrial invertebrates are determined by predator body size and species identity." *Ecology.* 2022. [PDF](paper-pdfs/miller-ter-kuile-2022.pdf).</li>

<li> **Bui, A**, D Orr, M Lepori-Bui, K Konicek, HS Young, HV Moeller. "Soil fungal community composition and functional similarity shift across distinct climatic conditions." *FEMS Microbiology Ecology.* 2020. [PDF](paper-pdfs/bui-2020.pdf).\
{{< fa newspaper >}} **Media coverage**: [UCSB Current](https://www.news.ucsb.edu/2020/020119/ancient-alliance), [The Bottom Line](https://thebottomline.as.ucsb.edu/2021/01/can-fungi-save-the-planet)</li>

<li> Miller-ter Kuile, A, D Orr, **A Bui**, R Dirzo, M Klope, DJ McCauley, C Motta, HS Young. "Impacts of rodent eradication on seed predation and plant community biomass." *Biotropica*. 2020. [PDF](paper-pdfs/miller-ter-kuile-2020.pdf).\
{{< fa newspaper >}} **Media coverage**: [UCSB Current](https://www.news.ucsb.edu/2020/020085/plot-twist), [The Economist](https://www.economist.com/science-and-technology/2020/10/31/kill-one-unwanted-species-and-another-arises), [Atlas Obscura](https://www.atlasobscura.com/articles/rats-coconuts-palmyra-atoll)</li>

<li> Lafferty, KD, JP McLaughlin, DS Gruner, TA Bogar, **A Bui**, JN Childress, M Espinosa, ES Forbes, CA Johnston, M Klope, A Miller-ter Kuile, M Lee, KA Plummer, DA Weber, RT Young, HS Young. "Secondary extinction of Asian tiger mosquitoes (Aedes albopictus) following rat eradication on Palmyra Atoll." *Biology Letters.* 2018. [PDF](paper-pdfs/lafferty-2018.pdf).\
{{< fa newspaper >}} **Media coverage**: [The Scientist](https://www.the-scientist.com/news-opinion/paradise-regained-how-the-palmyra-atoll-got-rid-of-invasive-mosquitoes-30063)</li>

<li> Hardesty-Moore, M, S Deinet, R Freeman, GC Titcomb, EM Dillon, K Stears, M Klope, **A Bui**, D Orr, HS Young, A Miller-ter Kuile, LF Hughey, DJ McCauley. "Migration in the Anthropocene: how collective navigation, environmental system, and taxonomy shape the vulnerability of migratory species." *Philosophical Transactions of the Royal Society B.* 2017. [PDF](paper-pdfs/hardesty-moore-2017.pdf).</li>

</ol>

## In review/revision

Orr, D, Z Zilz, E Duge, S Copeland, **A Bui**, CI Motta, A Swei, HS Young. "Context-dependent effects of wildlife and cattle on tick survivorship".\
Copeland, S, S Sambado, **A Bui**, D Orr, A Swei, HS Young. "Context-dependent effects of wildlife declines and livestock additions across a climatic gradient on tick abundance in southern California."

## Code note

I battled for a long time to make the reverse numbered list on this page work. If you want to implement this on your own website, the code for this page is [here](https://github.com/an-bui/website/blob/main/publications.qmd).
